# Generated by Django 5.0.9 on 2026-08-15 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("purpose", models.TextField(blank=True, verbose_name="purpose")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "expected_attendees",
                    models.PositiveIntegerField(
                        default=1, verbose_name="expected attendees"
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(db_index=True, verbose_name="start"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(db_index=True, verbose_name="end"),
                ),
                (
                    "booked_by_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="booked by"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="confirmed",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="cancellation reason"
                    ),
                ),
            ],
            options={
                "verbose_name": "booking",
                "verbose_name_plural": "bookings",
                "ordering": ("start_datetime",),
            },
        ),
        migrations.CreateModel(
            name="BookingSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("purpose", models.TextField(blank=True, verbose_name="purpose")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "expected_attendees",
                    models.PositiveIntegerField(
                        default=1, verbose_name="expected attendees"
                    ),
                ),
                (
                    "booked_by_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="booked by"
                    ),
                ),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("none", "One-off"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        default="weekly",
                        max_length=20,
                        verbose_name="recurrence",
                    ),
                ),
                (
                    "interval",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Every N days / weeks / months / years.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="interval",
                    ),
                ),
                (
                    "weekdays",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Weekly recurrences: 0 = Monday ... 6 = Sunday.",
                        verbose_name="weekdays",
                    ),
                ),
                (
                    "monthly_mode",
                    models.CharField(
                        choices=[
                            ("day_of_month", "Same day number every month"),
                            ("nth_weekday", "Nth weekday of the month"),
                        ],
                        default="day_of_month",
                        max_length=20,
                        verbose_name="monthly mode",
                    ),
                ),
                (
                    "month_day",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="day of month"
                    ),
                ),
                (
                    "nth_week",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="1 = first, 2 = second ... -1 = last week of the month.",
                        null=True,
                        verbose_name="nth week",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                ("start_time", models.TimeField(verbose_name="start time")),
                ("end_time", models.TimeField(verbose_name="end time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="confirmed",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
            ],
            options={
                "verbose_name": "booking series",
                "verbose_name_plural": "booking series",
                "ordering": ("-start_date",),
            },
        ),
    ]
