# Generated by Django 5.0.9 on 2026-08-15 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_initial"),
        ("employees", "0002_initial"),
        ("rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="required_resources",
            field=models.ManyToManyField(
                blank=True, related_name="bookings", to="rooms.resourcetype"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="rooms.room",
            ),
        ),
        migrations.AddField(
            model_name="bookingseries",
            name="booked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_series",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="bookingseries",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_series",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bookingseries",
            name="required_resources",
            field=models.ManyToManyField(
                blank=True, related_name="booking_series", to="rooms.resourcetype"
            ),
        ),
        migrations.AddField(
            model_name="bookingseries",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_series",
                to="rooms.room",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="occurrences",
                to="bookings.bookingseries",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["room", "start_datetime", "end_datetime"],
                name="bookings_bo_room_id_daddf4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "start_datetime"],
                name="bookings_bo_status_f6e1f8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("end_datetime__gt", models.F("start_datetime"))),
                name="booking_end_after_start",
            ),
        ),
    ]
