# Generated by Django 5.0.9 on 2026-09-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingseries',
            name='month_day',
        ),
        migrations.AddField(
            model_name='bookingseries',
            name='month_days',
            field=models.JSONField(blank=True, default=list, help_text="Monthly 'day of month' mode: which day numbers (1-31), several allowed.", verbose_name='days of month'),
        ),
        migrations.AddField(
            model_name='bookingseries',
            name='yearly_dates',
            field=models.JSONField(blank=True, default=list, help_text='Yearly recurrences: list of {month, day} pairs, several allowed.', verbose_name='yearly dates'),
        ),
    ]
