# Generated by Django 5.0.9 on 2026-08-15 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("booking_created", "Booking created"),
                            ("booking_cancelled", "Booking cancelled"),
                            ("booking_conflict", "Booking conflict"),
                            ("booking_reminder", "Upcoming booking"),
                            ("room_maintenance", "Room under maintenance"),
                            ("resource_issue", "Resource issue"),
                        ],
                        max_length=32,
                        verbose_name="category",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=16,
                        verbose_name="level",
                    ),
                ),
                (
                    "message_fr",
                    models.CharField(max_length=255, verbose_name="message (fr)"),
                ),
                (
                    "message_ar",
                    models.CharField(max_length=255, verbose_name="message (ar)"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="read")),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ("-created_at",),
            },
        ),
    ]
