# Generated by Django 5.0.9 on 2026-08-15 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResourceIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="resolved at"
                    ),
                ),
            ],
            options={
                "verbose_name": "resource issue",
                "verbose_name_plural": "resource issues",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ResourceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("code", models.SlugField(unique=True, verbose_name="code")),
                ("name_fr", models.CharField(max_length=120, verbose_name="name (fr)")),
                ("name_ar", models.CharField(max_length=120, verbose_name="name (ar)")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="icon"),
                ),
                (
                    "is_countable",
                    models.BooleanField(
                        default=True,
                        help_text="Chairs are counted, air conditioning is simply present or not.",
                        verbose_name="countable",
                    ),
                ),
            ],
            options={
                "verbose_name": "resource type",
                "verbose_name_plural": "resource types",
                "ordering": ("name_fr",),
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="name (ar)"
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=30, unique=True, verbose_name="code"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="capacity",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="location"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("maintenance", "Under maintenance"),
                            ("closed", "Closed"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#2563eb",
                        help_text="Used to colour the room's events in the calendar.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9a-fA-F]{3}){1,2}$", "Enter a hex colour."
                            )
                        ],
                        verbose_name="calendar colour",
                    ),
                ),
            ],
            options={
                "verbose_name": "room",
                "verbose_name_plural": "rooms",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="RoomResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="quantity"),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("ok", "Working"),
                            ("damaged", "Damaged"),
                            ("missing", "Missing"),
                        ],
                        default="ok",
                        max_length=20,
                        verbose_name="condition",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
            ],
            options={
                "verbose_name": "room resource",
                "verbose_name_plural": "room resources",
                "ordering": ("resource_type__name_fr",),
            },
        ),
    ]
