# Generated by Django 5.0.9 on 2026-08-15 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceissue",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["status", "deleted_at"], name="rooms_room_status_a50163_idx"
            ),
        ),
        migrations.AddField(
            model_name="resourceissue",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="rooms.room",
            ),
        ),
        migrations.AddField(
            model_name="roomresource",
            name="resource_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="room_resources",
                to="rooms.resourcetype",
            ),
        ),
        migrations.AddField(
            model_name="roomresource",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="rooms.room",
            ),
        ),
        migrations.AddField(
            model_name="resourceissue",
            name="room_resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="rooms.roomresource",
            ),
        ),
        migrations.AddConstraint(
            model_name="roomresource",
            constraint=models.UniqueConstraint(
                fields=("room", "resource_type"), name="unique_resource_per_room"
            ),
        ),
    ]
