# Generated by Django 5.0.9 on 2026-08-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="managed_rooms",
            field=models.ManyToManyField(
                blank=True,
                related_name="managers",
                to="rooms.room",
                verbose_name="managed rooms",
            ),
        ),
    ]
